name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Cache .NET 10 SDK
        uses: actions/cache@v4
        with:
          path: $HOME/.dotnet
          key: dotnet-10-${{ runner.os }}-${{ hashFiles('**/global.json') }}
          restore-keys: |
            dotnet-10-${{ runner.os }}-

      - name: Install .NET 10 SDK
        shell: bash
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          # install latest 10.x channel; replace --version <exact-version> if needed
          ./dotnet-install.sh --channel 10.0 --install-dir $HOME/.dotnet
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
      - name: Verify dotnet
        run: dotnet --info

      # # 1. Setup .NET 10 SDK
      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '10.0.x'
      
      # 2. Azure Static Web App Deployment Action
      - name: Build And Deploy Blazor WASM App
        id: swa
        uses: azure/static-web-apps-deploy@v1
        with:
          dotnet-version: '10.0.x'
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_PLANT_04DA70210 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "BlazorBootstrap.Demo.WebAssembly" # App source code path
          output_location: "wwwroot" # Built app content directory - optional
          app_build_command: 'dotnet publish --configuration Release --output build'

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_PLANT_04DA70210 }}
          action: "close"
